version: '3.8'

services:
  # Unified interactive firmware development environment
  firmware-env:
    build:
      context: .
      dockerfile: Dockerfile
    image: cpsl-ti-radar-firmware-dev:latest
    volumes:
      # Bind-mount the repository context
      - .:/build_context
    environment:
      - CGT_TI_ARM_CLANG_PATH=/opt/ti/ti-cgt-armllvm_2.1.2.LTS
      - CGT_TI_ARM_PATH=/opt/ti/ti-cgt-arm_20.2.7.LTS
      - MMWAVE_MCUPLUS_SDK_PATH=/opt/ti/mmwave_mcuplus_sdk_04_04_01_02
      - MMWAVE_SDK_PATH=/opt/ti/mmwave_sdk_03_06_02_00-LTS
      - SYSCONFIG_PATH=/opt/ti/sysconfig_1.28.0
      - RADAR_TOOLBOX_INSTALL_PATH=/opt/ti/radar_toolbox_4_00_00_05
    stdin_open: true
    tty: true
    command: /bin/bash
